UserManage/urls.py
from django.urls import path

from users.views import group, user, admin, task
from users.utils import code

urlpatterns = [
    # path('admin/', admin.site.urls),
    # 登录登出
    path("", user.user_list),
    path("login/", admin.login),
    path("logout/", admin.logout),
    path("image/code/", admin.image_code),
    # 管理员账户管理
    path("admin/list/", admin.admin_list),
    path("admin/add/", admin.admin_add),
    path("admin/edit/<int:admin_id>/", admin.admin_edit),
    path("admin/delete/<int:admin_id>/", admin.admin_delete),
    path("admin/reset/<int:admin_id>/", admin.admin_reset),
    # 组别管理
    path("group/list/", group.group_list),
    path("group/add/", group.group_add),
    path("group/edit/<int:group_id>", group.group_edit),
    path("group/delete/<int:group_id>/", group.group_delete),
    # 用户管理
    path("user/list/", user.user_list),
    path("user/add/", user.user_add),
    path("user/edit/<int:user_id>/", user.user_edit),
    path("user/delete/<int:user_id>/", user.user_delete),
    # 任务管理
    path("task/list/", task.task_list),
    path("task/ajax/", task.task_ajax),
    path("task/submit/", task.task_submit),
    path("task/delete/", task.task_delete),

]

users/models.py
from django.db import models

# Create your models here.
"""
数据库生成命令:
python manage.py makemigrations
python manage.py migrate
"""


class Admin(models.Model):
    """管理员类"""
    username = models.CharField(max_length=32, verbose_name="用户名")
    password = models.CharField(max_length=64, verbose_name="密码")

    # 定义返回值
    def __str__(self):
        return self.username


class Group(models.Model):
    """区分各用户组的功能"""
    group_name = models.CharField(max_length=32, verbose_name="用户组名称")

    # 定义返回值
    def __str__(self):
        return self.group_name


class User(models.Model):
    """用户类"""
    username = models.CharField(max_length=32, verbose_name="用户名")
    password = models.CharField(max_length=64, verbose_name="密码")
    email = models.CharField(max_length=32, verbose_name="邮箱")
    gender_choices = (
        (0, "女"),
        (1, "男"),
    )
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices)
    birthday = models.DateField(verbose_name="生日")
    account = models.IntegerField(verbose_name="账户余额", default=0)
    vip_end_time = models.DateTimeField(verbose_name="会员到期时间")
    group = models.ForeignKey(to="Group", to_field="id", verbose_name="用户组",
                              null=True, blank=True, on_delete=models.CASCADE)

    # 定义年龄方法
    def get_age(self):
        import datetime
        return int((datetime.datetime.now().date() - self.birthday).days / 365.25)


class Task(models.Model):
    """任务类"""
    level_choices = (
        (0, "简单"),
        (1, "中等"),
        (2, "困难"),
    )
    task_level = models.SmallIntegerField(verbose_name="任务等级", choices=level_choices)
    task_manager = models.ForeignKey(to="Admin", to_field="id", verbose_name="任务负责人", on_delete=models.CASCADE)
    task_name = models.CharField(max_length=32, verbose_name="任务名称")
    task_content = models.TextField(verbose_name="任务内容")

users/views/admin.py
from io import BytesIO

from django.http import HttpResponse
from django.shortcuts import render, redirect

from users import models
from users.utils.code import check_code
from users.utils.form import AdminForm, AdminFormEdit, AdminFormReset, LoginForm


# Create your views here.
def admin_list(request):
    admins = models.Admin.objects.all()
    return render(request, "admin_list.html", {"admins": admins})


def admin_add(request):
    title = "管理员账户添加"

    if request.method == "GET":
        admin_form = AdminForm()
        return render(request, "common_change.html", {"form": admin_form, "title": title})
    # 获取用户提交的数据
    admin_form = AdminForm(data=request.POST)
    # 校验数据
    if admin_form.is_valid():
        # 保存数据
        admin_form.save()
        # 跳转到用户组列表页面
        return redirect("/admin/list/")
    # 校验失败，admin_form.errors会带上错误信息
    return render(request, "common_change.html", {"form": admin_form, "title": title})


def admin_edit(request, admin_id):
    admin_name = models.Admin.objects.get(id=admin_id).username
    title = f"管理员名字修改:原名--{admin_name}"
    if request.method == "GET":
        # 将用户组对象传递给前端页面
        admin_form_edit = AdminFormEdit()
        return render(request, "common_change.html", {"form": admin_form_edit, "title": title})
    # 获取用户提交的数据
    admin_form_edit = AdminFormEdit(data=request.POST)
    # 校验数据
    if admin_form_edit.is_valid():
        # 修改数据
        admin = models.Admin.objects.get(id=admin_id)
        admin.username = admin_form_edit.cleaned_data.get("username")
        admin.save()
        # 跳转到用户组列表页面
        return redirect("/admin/list/")
    # 校验失败，admin_form.errors会带上错误信息
    return render(request, "common_change.html", {"form": admin_form_edit, "title": title})


def admin_delete(request, admin_id):
    models.Admin.objects.get(id=admin_id).delete()
    return redirect("/admin/list/")


def admin_reset(request, admin_id):
    name = models.Admin.objects.get(id=admin_id).username
    title = f"密码重置--{name}"
    if request.method == "GET":
        admin_form_reset = AdminFormReset()
        return render(request, "common_change.html", {"form": admin_form_reset, "title": title})
    # 获取用户提交的数据
    admin_form_reset = AdminFormReset(data=request.POST, instance=models.Admin.objects.get(id=admin_id))
    # 校验数据
    if admin_form_reset.is_valid():
        # 修改数据
        admin_form_reset.save()
        # 跳转到用户组列表页面
        return redirect("/admin/list/")
    # 校验失败，admin_form.errors会带上错误信息
    return render(request, "common_change.html", {"form": admin_form_reset, "title": title})


def login(request):
    """ 登录 """
    # 判断用户是否已经登录
    if request.session.get("username"):
        return redirect("/admin/list/")
    # 未登录则跳转到登录页面
    if request.method == "GET":
        login_form = LoginForm()
        return render(request, "login.html", {"form": login_form})
    # 获取用户登录数据
    login_form = LoginForm(data=request.POST)
    if login_form.is_valid():
        # 校验验证码
        user_input_code = login_form.cleaned_data.pop('image_code')
        code = request.session.get('image_code', "")
        if code.upper() != user_input_code.upper():
            login_form.add_error("image_code", "验证码错误")
            return render(request, 'login.html', {'form': login_form})
        # 校验用户名和密码
        username = login_form.cleaned_data.get("username")
        password = login_form.cleaned_data.get("password")
        if models.Admin.objects.filter(username=username, password=password).exists():
            request.session["username"] = username
            return redirect("/admin/list/")
        else:
            login_form.add_error("username", "用户名或密码错误")
            return render(request, "login.html", {"form": login_form})
    return render(request, "login.html", {"form": login_form})


def logout(request):
    """ 登出 """
    request.session.flush()
    return redirect("/login/")


def image_code(request):
    """ 生成图片验证码 """

    # 调用pillow函数，生成图片
    img, code_string = check_code()

    # 写入到自己的session中（以便于后续获取验证码再进行校验）
    request.session['image_code'] = code_string
    # 给Session设置60s超时
    request.session.set_expiry(60)

    stream = BytesIO()
    img.save(stream, 'png')
    return HttpResponse(stream.getvalue())

users/views/group.py
from django.shortcuts import render, redirect

from users import models
from users.utils.form import GroupForm


# Create your views here.
def group_list(request):
    groups = models.Group.objects.all()
    return render(request, "group_list.html", {"groups": groups})


def group_add(request):
    if request.method == "GET":
        group_form = GroupForm()
        return render(request, "group_add.html", {"group_form": group_form})
    # 获取用户提交的数据
    group_form = GroupForm(request.POST)
    # 校验数据
    if group_form.is_valid():
        # 保存数据
        group_form.save()
        # 跳转到用户组列表页面
        return redirect("/group/list/")


def group_edit(request, group_id):
    # 获取要编辑的用户组对象
    group = models.Group.objects.get(id=group_id)
    if request.method == "GET":
        # 将用户组对象传递给前端页面
        group_form = GroupForm(instance=group)
        return render(request, "group_edit.html", {"group_form": group_form})
    # 获取用户提交的数据
    group_form = GroupForm(request.POST, instance=group)
    # 校验数据
    if group_form.is_valid():
        # 亦可自定义一些数据
        # group_form.instance.group_name = "自定义"
        # 保存数据
        group_form.save()
        # 跳转到用户组列表页面
        return redirect("/group/list/")
    # 校验失败，group_form.errors会带上错误信息
    return render(request, "group_edit.html", {"group_form": group_form})


def group_delete(request, group_id):
    # 获取要删除的用户组对象
    group = models.Group.objects.get(id=group_id)
    # 删除用户组
    group.delete()
    # 跳转到用户组列表页面
    return redirect("/group/list/")

users/views/task.py
from django import forms
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from users import models
from users.utils.bootstrap import BootstrapModelForm


class TaskForm(BootstrapModelForm):
    class Meta:
        model = models.Task
        fields = "__all__"
        widgets = {
            "task_content": forms.TextInput(attrs={"class": "form-control"}),
        }


def task_list(request):
    task_form = TaskForm()
    tasks = models.Task.objects.all()
    return render(request, "task_list.html", {"form": task_form, "tasks": tasks})


@csrf_exempt
def task_ajax(request):
    a = request.GET.get("a")
    print(a)
    return HttpResponse(a)


@csrf_exempt
def task_submit(request):
    task_form = TaskForm(request.POST)
    print(task_form)
    if task_form.is_valid():
        task_form.save()
        return HttpResponse("ok")


@csrf_exempt
def task_delete(request):
    task_id = request.POST.get("task_id")
    print(task_id, type(task_id))
    try:
        task = models.Task.objects.get(id=task_id)
        task.delete()
        return HttpResponse("ok")
    except:
        return HttpResponse("删除失败")

users/views/user.py
from django.shortcuts import render, redirect

from users import models
from users.utils.form import UserForm


def user_list(request):
    users = models.User.objects.all()
    return render(request, "user_list.html", {"users": users})


def user_add(request):
    if request.method == "GET":
        user_form = UserForm()
        return render(request, "user_add.html", {"user_form": user_form})
    # 获取用户提交的数据
    user_form = UserForm(request.POST)
    # 校验数据
    if user_form.is_valid():
        # 保存数据
        user_form.save()
        # 跳转到用户列表页面
        return redirect("/user/list/")


def user_edit(request, user_id):
    # 获取要编辑的用户对象
    user = models.User.objects.get(id=user_id)
    if request.method == "GET":
        # 将用户对象传递给前端页面
        user_form = UserForm(instance=user)
        return render(request, "user_edit.html", {"user_form": user_form})
    # 获取用户提交的数据
    user_form = UserForm(request.POST, instance=user)
    # 校验数据
    if user_form.is_valid():
        # 亦可自定义校验规则
        if user_form.cleaned_data["username"] == "admin":
            user_form.add_error("username", "用户名不能为admin,你怕是要卡bug吗")
            return render(request, "user_edit.html", {"user_form": user_form})
        # 亦可制造埋点数据
        # user_form.instance.xxx = "123456"
        # 保存数据
        user_form.save()
        # 跳转到用户列表页面
        return redirect("/user/list/")
    # 校验失败，user_form.errors会带上错误信息
    return render(request, "user_edit.html", {"user_form": user_form})


def user_delete(request, user_id):
    # 获取要删除的用户对象
    user = models.User.objects.get(id=user_id)
    # 删除用户
    user.delete()
    # 跳转到用户列表页面
    return redirect("/user/list/")

users/templates/admin_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

users/templates/admin_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

users/templates/admin_list.html
{% extends "layout.html" %}

{% block style %}

{% endblock %}



{% block content %}
    <div class="container">
        <div style="margin: 20px auto 5px 0">
            <a href="/admin/add/">
                <button type="button" class="btn btn-success btn-sm">添加管理员</button>
            </a>
        </div>

        <div class="card">
            <div class="card-header">
                管理员列表
            </div>
            <div class="card-body">
                <table class="table table-hover table-bordered table-sm">
                    <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">管理员</th>
                        <th scope="col">密码</th>
                        <th scope="col">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for admin in admins %}
                        <tr>
                            <th scope="row">{{ admin.id }}</th>
                            <td>{{ admin.username }}</td>
                            <td>******</td>
                            <td>
                                <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                                    <a type="button" class="btn btn-primary btn-sm" href="/admin/edit/{{ admin.id }}">
                                        编辑
                                    </a>
                                    <a type="button" class="btn btn-secondary btn-sm" href="/admin/reset/{{ admin.id }}">
                                        重置密码
                                    </a>
                                    <a type="button" class="btn btn-danger btn-sm" href="/admin/delete/{{ admin.id }}">
                                        删除
                                    </a>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>



{% endblock %}

users/templates/common_change.html
{% extends "layout.html" %}

{% block content %}
    <div class="container">
        <div class="card" style="margin-top: 30px">
            <div class="card-header">
                {{ title }}
            </div>
            <div class="card-body">
                <div class="container" style="margin: 10px">
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {% for item in form %}
                            <div class="mb-1">
                                <lable>{{ item.label }}</lable>
                                {{ item }}
                                <span style="color: red;">{{ item.errors.0 }}</span>
                            </div>
                        {% endfor %}
                        {# 提交按钮 #}
                        <button class="btn btn-primary" type="submit">提交</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/group_add.html
{% extends "layout.html" %}

{% block content %}
    <div class="container">
        <div class="card" style="margin-top: 30px">
            <div class="card-header">
                添加组
            </div>
            <div class="card-body">
                <div class="container" style="margin: 10px">
                    <form method="post">
                        {% csrf_token %}
                        {% for item in group_form %}
                            <div class="mb-1">
                                <lable>{{ item.label }}</lable>
                                {{ item }}
                                <span style="color: red;">{{ field.errors.0 }}</span>
                            </div>
                        {% endfor %}
                        {# 提交按钮 #}
                        <button class="btn btn-primary" type="submit">提交</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/group_edit.html
{% extends "layout.html" %}

{% block content %}
    <div class="container">
        <div class="card" style="margin-top: 30px">
            <div class="card-header">
                修改组
            </div>
            <div class="card-body">
                <div class="container" style="margin: 10px">
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {% for item in group_form %}
                            <div class="mb-1">
                                <lable>{{ item.label }}</lable>
                                {{ item }}
                                <span style="color: red;">{{ item.errors.0 }}</span>
                            </div>
                        {% endfor %}
                        {# 提交按钮 #}
                        <button class="btn btn-danger" type="submit">确认修改</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/group_list.html
{% extends "layout.html" %}

{% block style %}

{% endblock %}



{% block content %}
    <div class="container">
        <div style="margin: 20px auto 5px 0">
            <a href="/group/add/">
                <button type="button" class="btn btn-success btn-sm">添加组</button>
            </a>
        </div>

        <div class="card">
            <div class="card-header">
                组别列表
            </div>
            <div class="card-body">
                <table class="table table-hover table-bordered table-sm">
                    <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">组名</th>
                        <th scope="col">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for group in groups %}
                        <tr>
                            <th scope="row">{{ group.id }}</th>
                            <td>{{ group.group_name }}</td>
                            <td>
                                <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                                    <a type="button" class="btn btn-primary btn-sm" href="/group/edit/{{ group.id }}">
                                        编辑
                                    </a>
                                    <a type="button" class="btn btn-danger btn-sm" href="/group/delete/{{ group.id }}">
                                        删除
                                    </a>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>



{% endblock %}

users/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>后台管理</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap5/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static "plugins/bootstrap-datepicker-1.10.0/dist/css/bootstrap-datepicker.css" %}">
    {% block css %} {% endblock %}
    <style>
        @font-face {
            font-family: 'CustomFont';
            src: url('{% static "fonts/LXGWWenKaiMono-Regular.ttf" %}');
        }

        body {
            font-family: "CustomFont", sans-serif !important;
        }

        .container {
            max-width: 960px;
        {#未知:不设置960px会导致不同的设备边框比例不一致#}
        }

        .card-body {
            padding: 0 !important;
        }

        .table {
            margin-bottom: 0 !important;
        }
    </style>
    {% block style %} {% endblock %}

</head>
<body>

{#导航栏#}
<nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd;" data-bs-theme="light">
    <div class="container">
        <a class="navbar-brand" href="#">后台管理</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03"
                aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor03">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/admin/list">管理员</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/group/list">组别管理</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/user/list">用户管理</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/task/list">任务管理</a>
                </li>

            </ul>
            <ul class="navbar-nav mb-2 mb-lg-0" style="margin-right: 0">
                <li class="nav-item">
                    <a class="nav-link" href="#"></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        {{ request.session.username }}
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">个人资料</a></li>
                        <li><a class="dropdown-item" href="/logout/">退出登录</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

{#正文#}
{% block content %} {% endblock %}


<script src="{% static 'plugins/js/jquery-3.7.1.js' %}"></script>
<script src="{% static 'plugins/bootstrap5/js/bootstrap.bundle.js' %}"></script>
<script src="{% static "plugins/bootstrap-datepicker-1.10.0/dist/js/bootstrap-datepicker.js" %}"></script>
<script src="{% static "plugins/bootstrap-datepicker-1.10.0/dist/locales/bootstrap-datepicker.zh-CN.min.js" %}"></script>
{% block js %} {% endblock %}
<script>
    {#时间选择插件#}
    $(function () {
        $("input[name='birthday'], input[name='vip_end_time']").datepicker({
            format: 'yyyy-mm-dd',
            startDate: '1900-01-01',
            language: 'zh-CN',
            autoclose: true,
        });
    })
</script>


</body>
</html>

users/templates/task_list.html
{% extends "layout.html" %}

{% block style %}

{% endblock %}


{% block content %}
    <div class="container">
        <div class="card" style="margin-top: 30px">
            <div class="card-header">
                添加任务
            </div>
            <div class="card-body">
                <form method="post" novalidate>
                    <div class="row container">
                        {% for foo in form %}
                            <div class="col-6">
                                <div class="form-group">
                                    <label>{{ foo.label }}</label>
                                    {{ foo }}
                                </div>
                            </div>
                        {% endfor %}
                    </div>

                    <div class="container" style="margin-top: 10px; margin-bottom: 10px">
                        <input id="btn-submit" type="button" class="btn btn-primary" value="提交">
                    </div>
                </form>
            </div>
        </div>

        <div class="card" style="margin-top: 30px">
            <div class="card-header">
                任务列表-基于ajax的异步请求实现增删改查
            </div>
            <div class="card-body">
                <table class="table table-hover table-bordered table-sm">
                    <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">任务级别</th>
                        <th scope="col">任务负责人</th>
                        <th scope="col">任务标题</th>
                        <th scope="col">任务内容</th>
                        <th scope="col">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for task in tasks %}
                        <tr>
                            <th scope="row">{{ task.id }}</th>
                            <td>{{ task.get_task_level_display }}</td>
                            <td>{{ task.task_manager }}</td>
                            <td>{{ task.task_name }}</td>
                            <td>{{ task.task_content }}</td>
                            <td>
                                <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                                    <a type="button" class="btn btn-primary btn-sm" id="btn-edit-{{ task.id }}">
                                        编辑
                                    </a>
                                    <a type="button" class="btn btn-danger btn-sm btn-delete" id="btn-delete-{{ task.id }}">
                                        删除
                                    </a>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>


        <hr>

        <div class="card">
            <div class="card-header">
                计数按钮实现
            </div>
            <div class="card-body">
                <label>
                    <input id="btn-count" type="button" class="btn btn-primary" value="点击我有惊喜">
                </label>
                <label for="countText">
                    <input type="text" id="countText" value="0" readonly>
                </label>
            </div>
        </div>
    </div>
{% endblock %}


{% block js %}
    <script type="text/javascript">
        $(function () {
            {#网页加载完成后执行的代码#}
            bindBtnCount();
            bindBtnSubmit();
            bindBtnDelete();
        });

        let count = 0;

        function bindBtnCount() {
            $('#btn-count').click(function () {
                $.ajax(
                    {
                        url: '/task/ajax/',
                        type: 'get',
                        data: {
                            'a': count
                        },
                        success: function (data) {
                            console.log(data);
                            count++;
                            $('#countText').val(count);
                        }
                    }
                );
            });

        }

        function bindBtnSubmit() {
            $('#btn-submit').click(function () {
                $.ajax(
                    {
                        url: '/task/submit/',
                        type: 'post',
                        data: $('form').serialize(),
                        success: function (data) {
                            // 提示添加成功
                            alert("添加成功");
                            // 刷新页面
                            window.location.reload();
                        }
                    }
                );
            });
        }

        function bindBtnDelete() {
            $('.btn-delete').click(function () {
                let that = $(this);  // 保存$(this)的引用
                $.ajax(
                    {
                        url: '/task/delete/',
                        type: 'post',
                        data: {
                            'task_id': that.attr('id').split('-')[2]
                        },
                        success: function (data) {
                            // 删除该行
                            that.parent().parent().parent().remove();
                            // 无需刷新页面
                            {#window.location.reload();#}
                        }
                    }
                );
            });
        }
    </script>

{% endblock %}

users/templates/user_list.html
{% extends "layout.html" %}


{% block content %}
    <div class="container">
        <div style="margin: 20px auto 5px 0">
            <a href="/user/add/">
                <button type="button" class="btn btn-success btn-sm">添加用户</button>
            </a>
        </div>

        <div class="card">
            <div class="card-header">
                用户列表
            </div>
            <div class="card-body">
                <table class="table table-hover table-bordered table-sm">
                    <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">用户名</th>
                        <th scope="col">性别</th>
                        <th scope="col">年龄</th>
                        <th scope="col">邮箱</th>
                        <th scope="col">到期时间</th>
                        <th scope="col">组别</th>
                        <th scope="col">账户余额</th>
                        <th scope="col">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in users %}
                        <tr>
                            <th scope="row">{{ user.id }}</th>
                            <td>{{ user.username }}</td>
                            <td>{{ user.get_gender_display }}</td>
                            <td>{{ user.get_age }}</td>
                            <td>{{ user.email }}</td>
                            <td>{{ user.vip_end_time|date:"Y/m/d" }}</td>
                            <td>{{ user.group }}</td>
                            <td>{{ user.account }}</td>
                            <td>
                                <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                                    <a type="button" class="btn btn-primary btn-sm" href="/user/edit/{{ user.id }}">
                                        编辑
                                    </a>
                                    <a type="button" class="btn btn-danger btn-sm" href="/user/delete/{{ user.id }}">
                                        删除
                                    </a>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>



{% endblock %}